---
# Dell EMC OpenManage Python SDK update helper modules
omsdk_repo_builder: "omdrivers.helpers.iDRAC.RepoBuilder"
omsdk_inventory_compare: "omdrivers.helpers.iDRAC.CompareInventory"

# Absolute folder path where Catalog file and Dell EMC Update Packages (DUPs)
# are going to be downloaded.
# Recommeded way:
# (1). Mount the Network Share (either CIFS or NFS) in the read-write mode on
# the system on which you are executing the ansible playbook. This will be stage
# the catalog and DUPs
# (2). Once the catalog file and all the DUPs are downloaded, then provide
# this network share to the firmware update module
dup_repo_path: "{{share_mnt}}"

# Download URL
dup_http_download_url: "downloads.dell.com"
dup_ftp_download_url: "ftp.dell.com"

# Protocol for downloading the DUPs
# Options: ["HTTP", "FTP"]
# Default: "HTTP"
dup_download_protocol: "HTTP"

# Catalog file name
dup_catalog_file_name: "Catalog"

# Apply firmware updates
apply_firmware_update: True

# Re-boot immediately for applying firmware updates
# Certain fimrware updates require that you should reboot the system 
reboot_firmware_update: False

# Wait for the Firmware Update from Respository JOB to be completed
firmware_update_job_wait: True
