namespace: dellemc
name: openmanage
version: 2.1.0
readme: README.md
authors:
- Rajeev Arakkal <Rajeev_Arakkal@Dell.com>
- Jagadeesh N V <Jagadeesh_N_V@Dell.com>
- Sajna N Shetty <Sajna_Shetty@Dell.com>
- Felix Stephen <Felix_S@Dell.com>
- Anooja Vardhineni <Anooja_Vardhineni@Dellteam.com>

description: OpenManage Ansible modules allow Data Center and IT
  administrators to use RedHat Ansible to automate and orchestrate the
  configuration and management of Dell EMC PowerEdge Servers and modular
  infrastructure. This is done by leveraging the management and automation
  capabilities built into Integrated Dell Remote Access Controller (iDRAC)
  and OpenManage Enterprise(OME).

license_file: 'COPYING.md'

tags: ['dellemc', 'openmanage', 'idrac', 'ome', 'openmanage_enterprise',
       'redfish', 'redfish_api', 'poweredge_servers', 'automation', 'devops']

dependencies: {}

repository: https://github.com/dell/dellemc-openmanage-ansible-modules/tree/collections

documentation: https://dell.github.io/dellemc-openmanage-ansible-modules

homepage: https://github.com/dell/dellemc-openmanage-ansible-modules

issues: https://github.com/dell/dellemc-openmanage-ansible-modules/issues
