---
- hosts: myhosts
  connection: local
  name: Dell-EMC-Ansible-iDRAC Modules
  gather_facts: False

  tasks:
  - name: Get System Inventory
    dellemc_idrac_inventory:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
    tags:
       - inventory

  - name: Export Server Configuration Profile (SCP)
    dellemc_idrac_export_scp:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
       share_name: "{{share_name}}"
       share_pwd:  "{{share_pwd}}"
       share_user: "{{share_user}}"
       scp_components: "RAID"
    tags:
       - exportscp

  - name: Setup iDRAC Users 
    dellemc_idrac_user:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
       user_name:  "{{user_name}}"
       user_pwd:   "{{user_pwd}}"
       user_priv:  "{{user_priv}}"
       state:      "{{user_state}}"
    tags:
       - users

  - name: Get Lifecycle Controller Status
    dellemc_idrac_lcstatus:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
    tags:
       - lcstatus

  - name: Export Lifecycle Controller Log
    dellemc_idrac_export_lclog:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
       share_name: "{{share_name}}"
       share_user: "{{share_user}}"
       share_pwd:  "{{share_pwd}}"
    tags:
       - log

  - name: Export TSR
    dellemc_idrac_export_tsr:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
       share_name: "{{share_name}}"
       share_user: "{{share_user}}"
       share_pwd:  "{{share_pwd}}"
    tags:
       - tsr

  - name: Change Power State
    dellemc_idrac_power:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
       state:      "{{power_state}}"
    tags:
       - power

  - name: Configure SNMP
    dellemc_idrac_snmp:
       idrac_ip:             "{{idrac_ip}}"
       idrac_user:           "{{idrac_user}}"
       idrac_pwd:            "{{idrac_pwd}}"
       share_name:           "{{share_name}}"
       share_user:           "{{share_user}}"
       share_pwd:            "{{share_pwd}}"
       share_mnt:            "{{share_mnt}}"
       snmp_enable:          "{{snmp_enable}}"
       snmp_protocol:        "{{snmp_protocol}}"
       snmp_community:       "{{snmp_community}}"
       snmp_discovery_port:  "{{snmp_discovery_port}}"
       snmp_trap_port:       "{{snmp_trap_port}}"
       state:                "{{snmp_state}}"
    tags:
       - snmp

  - name: Configure SNMP Alert 
    dellemc_idrac_snmp_alert:
       idrac_ip:             "{{idrac_ip}}"
       idrac_user:           "{{idrac_user}}"
       idrac_pwd:            "{{idrac_pwd}}"
       share_name:           "{{share_name}}"
       share_user:           "{{share_user}}"
       share_pwd:            "{{share_pwd}}"
       share_mnt:            "{{share_mnt}}"
       snmp_alert_dest:      "{{snmp_alert_dest}}"
       snmp_alert_dest_state: "{{snmp_alert_dest_state}}"
       snmpv3_user:          "{{snmpv3_user}}"
       state:                "{{snmp_alert_state}}"
    tags:
       - snmpalert

  - name: Configure CSIOR
    dellemc_idrac_csior:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
       share_name: "{{share_name}}"
       share_user: "{{share_user}}"
       share_pwd:  "{{share_pwd}}"
       share_mnt:  "{{share_mnt}}"
       state:      "{{csior_state}}"
    tags:
       - csior

  - name: Configure TLS
    dellemc_idrac_tls:
       idrac_ip:     "{{idrac_ip}}"
       idrac_user:   "{{idrac_user}}"
       idrac_pwd:    "{{idrac_pwd}}"
       share_name:   "{{share_name}}"
       share_user:   "{{share_user}}"
       share_pwd:    "{{share_pwd}}"
       share_mnt:    "{{share_mnt}}"
       tls_protocol: "{{tls_protocol}}"
       ssl_bits:     "{{ssl_bits}}"
    tags:
       - tls

  - name: Get LC Job Stattus
    dellemc_idrac_lc_job:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
       job_id:     "{{job_id}}"
       state:      "present"
    tags:
       - jobs

  - name: Delete the LC Job
    dellemc_idrac_lc_job:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
       job_id:     "{{job_id}}"
       state:      "absent"
    tags:
       - jobs

  - name: Delete LC Job Queue
    dellemc_idrac_lc_job:
       idrac_ip:   "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd:  "{{idrac_pwd}}"
       job_id:     "JID_CLEARALL"
       state:      "absent"
    tags:
       - jobq

  - name: Configure Syslog
    dellemc_idrac_syslog:
       idrac_ip:  "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd: "{{idrac_pwd}}"
       share_name: "{{share_name}}"
       share_user: "{{share_user}}"
       share_pwd: "{{share_pwd}}"
       share_mnt: "{{share_mnt}}"
       Servers: []
       state: "present"
    tags:
       - syslog

  - name: Configure TimeZone
    dellemc_idrac_timezone:
       idrac_ip:  "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd: "{{idrac_pwd}}"
       share_name: "{{share_name}}"
       share_user: "{{share_user}}"
       share_pwd: "{{share_pwd}}"
       share_mnt: "{{share_mnt}}"
       timezone:  "Asia/Kolkata"
    tags:
       - timezone

  - name: Configure NTP
    dellemc_idrac_ntp:
       idrac_ip:  "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd: "{{idrac_pwd}}"
       share_name: "{{share_name}}"
       share_user: "{{share_user}}"
       share_pwd: "{{share_pwd}}"
       share_mnt: "{{share_mnt}}"
       ntp_servers: "{{ntp_servers}}"
       state: "present"
    tags:
       - ntp

  - name: Configure Virtual Drives
    dellemc_idrac_virtual_drive:
       idrac_ip:  "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd: "{{idrac_pwd}}"
       share_name: "{{share_name}}"
       share_user: "{{share_user}}"
       share_pwd: "{{share_pwd}}"
       share_mnt: "{{share_mnt}}"
       virtual_drive_name: "vd0"
       span_depth: 1
       span_length: 1
       state: "present"
    tags:
       - vd

  - name: Firmware Update using a Repository from Network Share
    dellemc_idrac_firmware_update:
       idrac_ip:  "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd: "{{idrac_pwd}}"
       share_name: "{{share_name}}"
       share_user: "{{share_user}}"
       share_pwd: "{{share_pwd}}"
    tags:
       - fwupdate

  - name: Configure System Location
    dellemc_idrac_location:
       idrac_ip:  "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd: "{{idrac_pwd}}"
       share_name: "{{share_name}}"
       share_user: "{{share_user}}"
       share_pwd: "{{share_pwd}}"
       share_mnt: "{{share_mnt}}"
       data_center_name: "BLR-5 LAB-2"
    tags:
       - location

  - name: Get FW Inventory
    dellemc_idrac_sw_inventory:
       idrac_ip:  "{{idrac_ip}}"
       idrac_user: "{{idrac_user}}"
       idrac_pwd: "{{idrac_pwd}}"
       share_mnt: "{{share_mnt}}/Test"
       choice: "installed"
       serialize: False
    tags:
       - swinventory
