---
- hosts: hosts
  vars:
    retries_count: 30
    polling_interval: 15 #in seconds
  connection: local
  name: "OME - Catalog creation details tracking"
  gather_facts: False

  tasks:
  - name: "Triggers job for catalog creation."
    ome_firmware_catalog:
      hostname:  "{{ hostname }}"
      username: "{{ username }}"
      password:  "{{ password }}"
      catalog_name: catalog1
      catalog_description: HTTPS Desc
      source: downloads.company.com
      repository_type: HTTPS
      source_path: catalog
      file_name: catalog.gz
    register: result
    failed_when: "'catalog_status' not in result"

  - name: "Get job details using job id from ome firmware catalog creation."
    dellemc_ome_job_facts:
      hostname:  "{{ hostname }}"
      username: "{{ username }}"
      password:  "{{ password }}"
      job_id: "{{ result.catalog_status.TaskId }}"
    register: job_result
    failed_when: "'job_facts' not in job_result"
    until: job_result.job_facts.LastRunStatus.Name == 'Completed' or job_result.job_facts.LastRunStatus.Name == 'Failed'
    retries: "{{ retries_count }}"
    delay: "{{ polling_interval }}"

