---
- name: Converge file to update attributes with apply time as Immediate
  hosts: all
  gather_facts: false
  tasks:
    - name: Include the helper file
      ansible.builtin.include_tasks: ../__helper.yml

    - name: Pre-check - fail if enough disk not found to create VD on RAID 1
      ansible.builtin.fail:
        msg: 'Physical disks are not sufficient to proceed the test case need
             more than 2 and found {{ physicaldisks | length }}'
      when: "{{ physicaldisks | length }} < 2"

    - name: Removing if disks are assigned as hotspare and resetting the controller
      ansible.builtin.include_tasks: ../__helper.yml
      vars:
        reset_trigger: 1
        target: "{{ physicaldisks[0] }}"

    - name: Removing if disks are assigned as hotspare
      ansible.builtin.include_tasks: ../__helper.yml
      vars:
        target: "{{ physicaldisks[1] }}"
