---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Performing operation on the iDRAC device using default reset_type
      ansible.builtin.import_role:
        name: idrac_storage_controller
      vars:
        hostname: "{{ lookup('env', 'IDRAC_IP') }}"
        username: "{{ lookup('env', 'IDRAC_USER') }}"
        password: "{{ lookup('env', 'IDRAC_PASSWORD') }}"
        validate_certs: false
        reset_config: true
