---
  - name: Setting facts for downloading the Catalogs and DUPs from 'downloads.dell.com'
    set_fact:
      dup_download_url: "{{dup_http_download_url}}"
    when:
      dup_download_protocol == "HTTP"
    delegate_to: 127.0.0.1
    run_once: True

  - name: Setting facts for downloading the Catalogs and DUPs from ftp.dell.com
    set_fact:
      dup_download_url: "{{dup_ftp_download_url}}"
    when:
      dup_download_protocol == "FTP"
    delegate_to: 127.0.0.1
    run_once: True

  - name: Download Catalog and prepare Catalog for firmware in scope
    command: python -m "{{omsdk_repo_builder}}" --protocol "{{dup_download_protocol}}" --site "{{dup_download_url}}" --folder "{{dup_repo_path}}" --catalog "{{dup_catalog_file_name}}" --verbose --download-catalog --build-catalog
    delegate_to: 127.0.0.1
    run_once: True

  - name: Download DellEMC Update Packages (DUPs) as per the scoped catalog
    command: python -m "{{omsdk_repo_builder}}" --folder "{{dup_repo_path}}" --verbose --download-dups
    delegate_to: 127.0.0.1
    run_once: True

  - name: Perform hash check of the downloaded DUPs
    command: python -m "{{omsdk_repo_builder}}" --folder "{{dup_repo_path}}" --protocol HashCheck
    delegate_to: 127.0.0.1
    run_once: True

  - name: Update firmware from the repository
    dellemc_idrac_firmware_update:
      idrac_ip:          "{{idrac_ip}}"
      idrac_user:        "{{idrac_user}}"
      idrac_pwd:         "{{idrac_pwd}}"
      share_name:        "{{share_name}}"
      share_user:        "{{share_user}}"
      share_pwd:         "{{share_pwd}}"
      catalog_file_name: "{{dup_catalog_file_name}}"
      apply_update:      "{{apply_firmware_update}}"
      reboot:            "{{reboot_firmware_update}}"
      job_wait:          "{{firmware_update_job_wait}}"
