---
- hosts: hosts
  connection: local
  name: Configure Secure Boot Mode
  gather_facts: False

  tasks:
  - name: Configure Secure Boot Mode
    dellemc_configure_bios:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/NFSShare"
       share_pwd: "share_pwd"
       share_user: "share_user"
       share_mnt:  "/mnt/mntpoint"
       secure_boot_mode: "AuditMode"
