--- 
- 
  connection: local
  gather_facts: false
  hosts: hosts
  name: Booting to Network Operating System image
  tasks: 
    - name: "Booting to Network Operating System image"
      dellemc_boot_to_network_iso: 
        idrac_ip: "x.x.x.x"
        idrac_pwd: "pwd"
        idrac_user: "user"
        share_name: "x.x.x.x:/NFSShare"
        share_pwd: "share_pwd"
        share_user: "share_user"
        iso_image: "uninterrupted_os_installation_image.iso."        
