---
- hosts: hosts
  connection: local
  name: Configure Server Power Setting
  gather_facts: False

  tasks:
  - name: Configure Server Power Setting
    dellemc_change_power_state:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       change_power: "PushPowerButton"

