---
- hosts: hosts
  connection: local
  name: Configure iDRAC CSIOR Setting
  gather_facts: False

  tasks:
  - name: Configure iDRAC CSIOR Setting
    dellemc_idrac_lc_attributes:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/NFSShare"
       share_pwd: "share_pwd"
       share_user: "share_user"
       share_mnt:  "/mnt/mntpoint"
       csior: "Enabled"
