---
- hosts: hosts
  connection: local
  name: Delete LC job Queue
  gather_facts: False

  tasks:
  - name: Delete LC job Queue
    dellemc_delete_lc_job_queue:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"

