---
- hosts: hosts
  connection: local
  name: Deleting a LC job
  gather_facts: False

  tasks:
  - name: Delete a LC job 
    dellemc_delete_lc_job:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       job_id: "JID_123456789"
