---
- hosts: myhosts
  connection: local
  name: DellEMC_OpenManage_Ansible_Modules_version_1.0.105
  gather_facts: False

  tasks:
  - name: bootmode_change
    dellemc_configure_bios:
       idrac_ip:   "x.x.x.x"
       idrac_user: "root"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/nfsfileshare"
       share_pwd: "share_pwd"
       share_user: "share_user"
       share_mnt:  "/mnt/mntpoint"
       boot_mode: "Bios"

    tags:
       - bootmode

  - name: nvme_configuration
    dellemc_configure_bios:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/nfsfileshare"
       share_pwd: "share_pwd"
       share_user: "share_user"
       share_mnt:  "/mnt/mntpoint"
       nvme_mode: "Raid"

    tags:
       - nvme
  
  - name: onetime_boot_mode
    dellemc_configure_bios:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"  
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/nfsfileshare"
       share_pwd: "share_pwd"
       share_user: "share_user"
       share_mnt:  "/mnt/mntpoint"
       onetime_boot_mode: "OneTimeHddSeq"

    tags:
       - onetimeboot
  
  - name: secure_boot_mode
    dellemc_configure_bios:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/nfsfileshare"
       share_pwd: "share_pwd"
       share_user: "share_user"
       share_mnt:  "/mnt/mntpoint"
       secure_boot_mode: "AuditMode"

    tags:
       - secureboot

  - name: boot_sequence
    dellemc_configure_bios:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/nfsfileshare"
       share_pwd: "share_pwd"
       share_user: "user"
       share_mnt:  "/mnt/mntpoint"
       boot_mode: "Bios"
       boot_sequence: "HardDisk.List.1-1"

    tags:
       - bootseq
