---
- hosts: hosts
  connection: local
  name: Export Server Configuration Profile to local folder
  gather_facts: False

  tasks:
  - name: Export Server Configuration Profile to local folder 
    dellemc_export_server_config_profile:
       idrac_ip:        "x.x.x.x"
       idrac_user:      "user"
       idrac_pwd:       "pwd"
       idrac_port:      "443"
       share_name:      "/var/localfolder"
       share_user:      "share_user"
       share_pwd:       "share_pwd"
       scp_components:  "BIOS"
       job_wait:        "True"
    
