---
- hosts: hosts
  connection: local
  name: Check LC Ready Status
  gather_facts: False

  tasks:
  - name: Check LC Ready Status
    dellemc_get_lcstatus:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"

