---
- hosts: hosts
  connection: local
  name: Configure the iDRAC user attributes
  gather_facts: False

  tasks:
  - name: Configure the iDRAC user attributes
    dellemc_configure_idrac_users:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/NFSShare"
       share_pwd: "share_pwd"
       share_user: "share_user"
       share_mnt:  "/mnt/mntpoint"
       action: "delete"
       user_name: "test"
