---
- hosts: hosts
  connection: local
  name: Configure the iDRAC users attributes
  gather_facts: False

  tasks:
  - name: Configure the iDRAC users attributes
    dellemc_configure_idrac_users:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/NFSShare"
       share_pwd: "Share_pwd"
       share_user: "Share_user"
       share_mnt:  "/mnt/mntpoint"
       action: "create"
       user_name: "user_name"
       user_password: "user_pwd"
       privilege_users: 'Administrator'
       ipmilanprivilege_users: 'Operator'
       ipmiserialprivilege_users: 'Administrator'
       enable_users: 'Enabled'
       solenable_users: 'Enabled'
       protocolenable_users: 'Enabled'
       privacyprotocol_users: 'DES'
       authenticationprotocol_users: 'MD5'
