---
- hosts: hosts
  connection: local
  name: Configure the iDRAC services attributes
  gather_facts: False

  tasks:
  - name: Configure the iDRAC services attributes
    dellemc_configure_idrac_services:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/NFSSahre"
       share_pwd: "share_pwd"
       share_user: "share_user"
       share_mnt:  "/mnt/mntpoint"
       snmp_enable: "Enabled"
       snmp_protocol: "All"
