---
- hosts: hosts
  connection: local
  name: Configure the iDRAC network attributes
  gather_facts: False

  tasks:
  - name: Configure the iDRAC network attributes
    dellemc_configure_idrac_network:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/NFSShare"
       share_pwd: "Share_pwd"
       share_user: "Share_user"
       share_mnt:  "/mnt/mntpoint"
       enable_nic: "Enabled"
       nic_selection: "Dedicated"
       failover_network: "T_None"
       auto_detect: "Disabled"
       auto_negotiation: "Enabled"
       network_speed: "T_1000"
       duplex_mode: "Full"
