---
- hosts: hosts
  connection: local
  name: Configure the iDRAC network attributes
  gather_facts: False

  tasks:
  - name: Configure the iDRAC network attributes
    dellemc_configure_idrac_network:
       idrac_ip:   "x.x.x.x"
       idrac_user: "user"
       idrac_pwd:  "pwd"
       share_name: "x.x.x.x:/NFSShare"
       share_pwd: "share_pwd"
       share_user: "Share_user"
       share_mnt:  "/mnt/mntpoint"
       enable_dhcp: "Enabled"
       dns_from_dhcp: "Enabled"
       enable_ipv4: "Enabled"
