---
- hosts: all
  name: Lifecycle Controller JOBs
  connection: local
  gather_facts: False

  tasks:
    - name: Get LC Job Status
      dellemc_idrac_lc_job:
        idrac_ip:   "{{idrac_ip}}"
        idrac_user: "{{idrac_user}}"
        idrac_pwd:  "{{idrac_pwd}}"
        job_id:     "JID_123456789012"
        state:      "present"

    - name: Delete the LC Job
      dellemc_idrac_lc_job:
        idrac_ip:   "{{idrac_ip}}"
        idrac_user: "{{idrac_user}}"
        idrac_pwd:  "{{idrac_pwd}}"
        job_id:     "JID_123456789012"
        state:      "absent"
