---
- hosts: all
  connection: local
  name: Configure LC attributes such as CSIOR
  gather_facts: False

  tasks:
  - name: Enable CSIOR
    dellemc_idrac_lc_attr:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
      csior:      "Enabled"

  - name: Disable CSIOR
    dellemc_idrac_lc_attr:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
      csior:      "Disabled"
