---
- hosts: all
  connection: local
  name: Get the LC status
  gather_facts: False

  tasks:
  - name: Get LC status
    dellemc_idrac_lcstatus:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
