---
- hosts: hosts
  connection: local
  name: Export Lifecycle Controller Logs
  gather_facts: False

  tasks:
  - name: Export Lifecycle Controller Logs
    dellemc_export_lc_logs:
       idrac_ip: "x.x.x.x"
       idrac_user: "user"
       idrac_pwd: "pwd"
       share_name: "x.x.x.x:/NFSShare"
       share_pwd: "share_pwd"
       share_user: "share_user"
       job_wait: "True"

