---
- hosts: hosts
  connection: local
  name: Dell OpenManage Ansible device Template service.
  gather_facts: False

  tasks:
  - name: "Create a template from a reference device."
    ome_template:
      hostname: "{{hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      device_id: 25123
      attributes:
        Name: "New Template"
        Description: "New Template description"

  - name: "Modify template name, description, and attribute value."
    ome_template:
      hostname: "{{hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      state: "modify"
      template_id: 1234
      attributes:
        Name: "New Custom Template"
        Description: "Custom Template Description"
        # Attributes to be modified in the template.
        # For information on any attribute id, use API /TemplateService/Templates(Id)/Views(Id)/AttributeViewDetails
        # This section is optional
        Attributes:
          - Id: 1234
            Value: "Test Attribute"
            IsIgnored: false

  - name: "Deploys template on multiple devices and changes the device level attributes. After the template is deployed,
an operating system can be installed using its image."
    ome_template:
      hostname: "{{hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      state: "deploy"
      template_id: 1234
      device_id:
        - 12765
        - 10173
      device_service_tag:
        - 'SVTG123'
        - 'SVTG456'
      attributes:
        # Device specific attributes to be modified during deployment.
        # For information on any attribute id, use API /TemplateService/Templates(Id)/Views(Id)/AttributeViewDetails
        # This section is optional
        Attributes:
          # specific device where attribute to be modified at deployment run-time.
          # The DeviceId should be mentioned above in the 'device_id' section.
          # Service tags not allowed.
          - DeviceId: 12765
            Attributes:
              - Id : 15645
                Value : "0.0.0.0"
                IsIgnored : false
          - DeviceId: 10173
            Attributes:
              - Id : 18968,
                Value : "hostname-1"
                IsIgnored : false
        # Include this to install operating system on the devices.
        # This section is optional
        NetworkBootIsoModel:
          BootToNetwork: false
          ShareType: "NFS"
          IsoPath: "/home/iso_path/filename.iso"
          ShareDetail:
            IpAddress: "192.168.0.2"
            ShareName: "sharename"
            User: "share_user"
            Password: "share_password"
        Options:
          EndHostPowerState: 1
          ShutdownType: 0
          TimeToWaitBeforeShutdown: 300
        Schedule:
          RunLater: true
          RunNow: false

