---
- hosts: myhosts
  connection: local
  name: Power Control for Dell EMC PowerEdge Servers
  gather_facts: False

  tasks:
  - name: PowerOn a PowerEdge Server
    dellemc_idrac_power:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
      state:      "PowerOn"

  - name: Soft Power Cycle a PowerEdge Server
    dellemc_idrac_power:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
      state:      "SoftPowerCycle"

  - name: Graceful shutdown a PowerEdge Server
    dellemc_idrac_power:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{idrac_pwd}}"
      state:      "GracefulPowerOff"
