---
- hosts: myhosts
  connection: local
  name: SNMP Agent configuration
  gather_facts: False

  tasks:
  - name: Enable SNMP 
    dellemc_idrac_snmp:
      idrac_ip:          "{{idrac_ip}}"
      idrac_user:        "{{idrac_user}}"
      idrac_pwd:         "{{idrac_pwd}}"
      share_name:        "{{share_name}}"
      share_user:        "{{share_user}}"
      share_pwd:         "{{share_pwd}}"
      share_mnt:         "{{share_mnt}}"
      snmp_enable:       "Enabled"
      snmp_protocol:     "All"
      snmp_community:    "public"
      snmp_port:         161
      snmp_trap_port:    162
      snmp_tarp_format:  "SNMPv1"

  - name: Change community string
    dellemc_idrac_snmp:
      idrac_ip:       "{{idrac_ip}}"
      idrac_user:     "{{idrac_user}}"
      idrac_pwd:      "{{idrac_pwd}}"
      share_name:     "{{share_name}}"
      share_user:     "{{share_user}}"
      share_pwd:      "{{share_pwd}}"
      share_mnt:      "{{share_mnt}}"
      snmp_community: "new_community_string"

  - name: Disable SNMP
    dellemc_idrac_snmp:
      idrac_ip:       "{{idrac_ip}}"
      idrac_user:     "{{idrac_user}}"
      idrac_pwd:      "{{idrac_pwd}}"
      share_name:     "{{share_name}}"
      share_user:     "{{share_user}}"
      share_pwd:      "{{share_pwd}}"
      share_mnt:      "{{share_mnt}}"
      snmp_enable:    "Disabled"
