---
- hosts: myhosts
  connection: local
  name: Configure Alert Destinations
  gather_facts: False

  tasks:
  - name: Add SNMP Alert Destinations
    dellemc_idrac_snmp_alert:
      idrac_ip:         "{{idrac_ip}}"
      idrac_user:       "{{idrac_user}}"
      idrac_pwd:        "{{idrac_pwd}}"
      share_name:       "{{share_name}}"
      share_user:       "{{share_user}}"
      share_pwd:        "{{share_pwd}}"
      share_mnt:        "{{share_mnt}}"
      snmp_alert_dest:
        - {"dest_address": "192.168.10.11", "state": 'Enabled'}
        - {"dest_address": "192.168.10.12", "state": 'Enabled'}
      state:            "present"

  - name: Enable SNMP Alerts
    dellemc_idrac_snmp_alert:
      idrac_ip:         "{{idrac_ip}}"
      idrac_user:       "{{idrac_user}}"
      idrac_pwd:        "{{idrac_pwd}}"
      share_name:       "{{share_name}}"
      share_user:       "{{share_user}}"
      share_pwd:        "{{share_pwd}}"
      share_mnt:        "{{share_mnt}}"
      snmp_alert_dest:
        - {"dest_address": "192.168.10.11", "state": 'Enabled'}
        - {"dest_address": "192.168.10.12", "state": 'Enabled'}
      state:            "present"

  - name: Disable SNMP Alerts
    dellemc_idrac_snmp_alert:
      idrac_ip:         "{{idrac_ip}}"
      idrac_user:       "{{idrac_user}}"
      idrac_pwd:        "{{idrac_pwd}}"
      share_name:       "{{share_name}}"
      share_user:       "{{share_user}}"
      share_pwd:        "{{share_pwd}}"
      share_mnt:        "{{share_mnt}}"
      snmp_alert_dest:
        - {"dest_address": "192.168.10.11", "state": 'Disabled'}
        - {"dest_address": "192.168.10.12", "state": 'Enabled'}
      state:            "present"

  - name: Remove SNMP Alert 
    dellemc_idrac_snmp_alert:
      idrac_ip:         "{{idrac_ip}}"
      idrac_user:       "{{idrac_user}}"
      idrac_pwd:        "{{idrac_pwd}}"
      share_name:       "{{share_name}}"
      share_user:       "{{share_user}}"
      share_pwd:        "{{share_pwd}}"
      share_mnt:        "{{share_mnt}}"
      snmp_alert_dest:
        - {"dest_address": "192.168.10.11"}
        - {"dest_address": "192.168.10.12"}
      state:            "absent"
