---
- hosts: myhosts
  name: Remote Syslog configuration
  connection: local
  gather_facts: False

  tasks:
    - name: Enable Syslog
      dellemc_idrac_syslog:
        idrac_ip : "{{idrac_ip}}"
        idrac_user: "{{idrac_user}}"
        idrac_pwd:  "{{idrac_pwd}}"
        share_name: "{{share_name}}"
        share_user: "{{share_user}}"
        share_pwd:  "{{share_pwd}}"
        share_mnt:  "{{share_mnt}}"
        syslog_servers: ["192.168.10.10"]
        syslog_port: 514
        state:      "present"

    - name: Add a new remote syslog server
      dellemc_idrac_syslog:
        idrac_ip : "{{idrac_ip}}"
        idrac_user: "{{idrac_user}}"
        idrac_pwd:  "{{idrac_pwd}}"
        share_name: "{{share_name}}"
        share_user: "{{share_user}}"
        share_pwd:  "{{share_pwd}}"
        share_mnt:  "{{share_mnt}}"
        syslog_servers: ["192.168.10.10", "192.168.10.11"]
        state:      "present"

    - name: Disable Syslog
      dellemc_idrac_syslog:
        idrac_ip : "{{idrac_ip}}"
        idrac_user: "{{idrac_user}}"
        idrac_pwd:  "{{idrac_pwd}}"
        share_name: "{{share_name}}"
        share_user: "{{share_user}}"
        share_pwd:  "{{share_pwd}}"
        share_mnt:  "{{share_mnt}}"
        state:      "absent"
