---
- hosts: all
  name: Configure Timezone and NTP settings on iDRAC
  connection: local
  gather_facts: False

  tasks:
  - name: Configure TimeZone and NTP
    dellemc_idrac_timezone_ntp:
      idrac_ip:    "{{idrac_ip}}"
      idrac_user:  "{{idrac_user}}"
      idrac_pwd:   "{{idrac_pwd}}"
      share_name:  "{{share_name}}"
      share_user:  "{{share_user}}"
      share_pwd:   "{{share_pwd}}"
      share_mnt:   "{{share_mnt}}"
      timezone:    "Asia/Kolkata"
      ntp_servers: ["143.166.255.33", "143.166.255.32"]
      state:       "present"

  - name: Change Timezone
    dellemc_idrac_timezone_ntp:
      idrac_ip:    "{{idrac_ip}}"
      idrac_user:  "{{idrac_user}}"
      idrac_pwd:   "{{idrac_pwd}}"
      share_name:  "{{share_name}}"
      share_user:  "{{share_user}}"      
      share_pwd:   "{{share_pwd}}"
      share_mnt:   "{{share_mnt}}"   
      timezone:    "US/Eastern"
      state:       "present"


  - name: Disable NTP
    dellemc_idrac_timezone_ntp:
      idrac_ip:    "{{idrac_ip}}"
      idrac_user:  "{{idrac_user}}"
      idrac_pwd:   "{{idrac_pwd}}"
      share_name:  "{{share_name}}"         
      share_user:  "{{share_user}}"                
      share_pwd:   "{{share_pwd}}"
      share_mnt:   "{{share_mnt}}"
      state:       "absent"
