---
- hosts: myhosts
  connection: local
  name: Users Administration
  gather_facts: False

  tasks:
  - name: Add a user
    dellemc_idrac_user:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
      share_name: "{{share_name}}"
      share_user: "{{share_user}}"
      share_pwd:  "{{share_pwd}}"
      share_mnt:  "{{share_mnt}}"
      user_name:  "newuser"
      user_pwd:   "password"
      user_priv:  "Administrator"
      state:      "present"

  - name: Change Password
    dellemc_idrac_user:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
      share_name: "{{share_name}}"
      share_user: "{{share_user}}"
      share_pwd:  "{{share_pwd}}"
      share_mnt:  "{{share_mnt}}"
      user_name:  "newuser"
      user_pwd:   "newpassword"
      state:      "present"

  - name: Change privilges
    dellemc_idrac_user:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
      share_name: "{{share_name}}"
      share_user: "{{share_user}}"
      share_pwd:  "{{share_pwd}}"
      share_mnt:  "{{share_mnt}}"
      user_name:  "newuser"
      user_pwd:   "newpassword"
      user_priv:  "Operator"
      state:      "present"

  - name: Disable User
    dellemc_idrac_user:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
      share_name: "{{share_name}}"
      share_user: "{{share_user}}"
      share_pwd:  "{{share_pwd}}"
      share_mnt:  "{{share_mnt}}"
      user_name:  "newuser"
      state:      "disable"

  - name: Enable User
    dellemc_idrac_user:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
      share_name: "{{share_name}}"
      share_user: "{{share_user}}"
      share_pwd:  "{{share_pwd}}"
      share_mnt:  "{{share_mnt}}"
      user_name:  "newuser"
      state:      "enable"

  - name: Remove User
    dellemc_idrac_user:
      idrac_ip:   "{{idrac_ip}}"
      idrac_user: "{{idrac_user}}"
      idrac_pwd:  "{{idrac_pwd}}"
      share_name: "{{share_name}}"
      share_user: "{{share_user}}"
      share_pwd:  "{{share_pwd}}"
      share_mnt:  "{{share_mnt}}"
      user_name:  "newuser"
      state:      "absent"
