---
- hosts: all
  connection: local
  name: Create / Delete Virtual Drive
  gather_facts: False

  tasks:
  - name: Create a virtual drive with 4 physical disks and raid level = RAID 10
    dellemc_idrac_virtual_drive:
      idrac_ip:        "{{idrac_ip}}"
      idrac_user:      "{{idrac_user}}"
      idrac_pwd:       "{{idrac_pwd}}"
      share_name:      "{{share_name}}"
      share_user:      "{{share_user}}"
      share_pwd:       "{{share_pwd}}"
      share_mnt:       "{{share_mnt}}"
      vd_name:         "VD_RAID10"
      controller_fqdd: "RAID.Integrated.1-1"
      raid_level:      "RAID 10"
      media_type:      "HDD"
      bus_protocol:    "SAS"
      stripe_size:     65536
      span_length:     4
      span_depth:      2
      state:           "present"

  # Create a virtual drive with RAID 5 and a span length of 5 physical disks
  # if no slot numbers are provided, then virtual drive will be created using
  # the physical disks that are available. If no Virual Disk size is specified,
  # then the size of the virtual disks will be auto-determined based on the
  # RAID level
  # For e.g., in the below example, if all the Physical Disks are of capacity
  # of 200GB and no vd_size is specified, then the Virtual Disk will be created
  # with space efficiency of (1-1/n = 1-1/5 = 80% of 1000GB = 800GB)

  - name: Create a virtual drive with 5 physical disks and RAID level = RAID 5
    dellemc_idrac_virtual_drive:
      idrac_ip:         "{{idrac_ip}}"
      idrac_user:       "{{idrac_user}}"
      idrac_pwd:        "{{idrac_pwd}}"
      share_name:       "{{share_name}}"
      share_user:       "{{share_user}}"
      share_pwd:        "{{share_pwd}}"
      share_mnt:        "{{share_mnt}}"
      vd_name:          "Virtual_Drive_0"
      controller_fqdd:  "RAID.Integrated.1-1"
      raid_level:       "RAID 5"
      media_type:       "HDD"
      bus_protocol:     "SAS"
      stripe_size:      65536
      span_depth:       1
      span_length:      5
      state:            "present"


  # Create a virtual drive with RAID 5 and physical disks having slot numbers
  # 0, 1, 2, 3, 4 and 5.

  - name: Create VD
    dellemc_idrac_virtual_drive:
      idrac_ip:         "{{idrac_ip}}"
      idrac_user:       "{{idrac_user}}"
      idrac_pwd:        "{{idrac_pwd}}"
      share_name:       "{{share_name}}"
      share_user:       "{{share_user}}"
      share_pwd:        "{{share_pwd}}"
      share_mnt:        "{{share_mnt}}"
      vd_name:          "Virtual_Drive_0"
      controller_fqdd:  "RAID.Integrated.1-1"
      pd_slots:         [0, 1, 2, 3, 4, 5]
      raid_level:       "RAID 5"
      media_type:       "HDD"
      bus_protocol:     "SAS"
      stripe_size:      65536
      span_depth:       1
      state:            "present"

  - name: Delete a virtual drive
    dellemc_idrac_virtual_drive:
      idrac_ip:        "{{idrac_ip}}"
      idrac_user:      "{{idrac_user}}"
      idrac_pwd:       "{{idrac_pwd}}"
      share_name:      "{{share_name}}"
      share_user:      "{{share_user}}"
      share_pwd:       "{{share_pwd}}"
      share_mnt:       "{{share_mnt}}"
      vd_name:         "VD_RAID10"
      controller_fqdd: "RAID.Integrated.1-1"
      state:           "absent"

