---
- hosts: hosts
  connection: local
  name: iDRAC storage volume configuration.
  gather_facts: False

  tasks:
  - name: Delete single volume.
    dellemc_idrac_storage_volume:
      idrac_ip:    "xx.xxx.xx.xx"
      idrac_user:  "xxxx"
      idrac_pwd:   "xxxxxxxx"
      state: "delete"
      vd_values:
        - vd_name: "volume_1"
