---
- hosts: hosts
  connection: local
  name: iDRAC storage volume configuration.
  gather_facts: False

  tasks:
  - name: View specific volume details.
    dellemc_idrac_storage_volume:
      idrac_ip:    "xx.xxx.xx.xx"
      idrac_user:  "xxxx"
      idrac_pwd:   "xxxxxxxx"
      state: "view"
      controller_id: "RAID.Slot.1-1"
      vd_id: "Disk.Virtual.0:RAID.Slot.1-1"
