---
- hosts: hosts
  connection: local
  name: iDRAC storage volume configuration.
  gather_facts: False

  tasks:
  - name: View all volume details.
    dellemc_idrac_storage_volume:
      idrac_ip:    "xx.xxx.xx.xx"
      idrac_user:  "xxxx"
      idrac_pwd:   "xxxxxxxx"
      state: "view"
