---
- hosts: hosts
  connection: local
  name: iDRAC storage volume configuration.
  gather_facts: False

  tasks:
  - name: Create multiple volume.
    dellemc_idrac_storage_volume:
        idrac_ip:    "xx.xxx.xx.xx"
        idrac_user:  "xxxx"
        idrac_pwd:   "xxxxxxxx"
        raid_reset_config: "True"
        state: "create"
        controller_fqdd: "RAID.Slot.1-1"
        raid_level: "RAID 1"
        span_depth: 1
        span_length: 2
        number_dedicated_hot_spare: 1
        disk_cache_policy: "Enabled"
        write_cache_policy: "WriteBackForce"
        read_cache_policy: "ReadAhead"
        stripe_size: 65536
        size: 100
        raid_init_operation: "Fast"
        vd_values:
          - vd_name: "volume_1"
            pd_slots: [2,1]
          - vd_name: "volume_2"
            raid_level: "RAID 5"
            span_length: 3
            span_depth: 1 
            pd_slots: [7,3,5]
            disk_cache_policy: "Disabled"
            write_cache_policy: "WriteBack"
            read_cache_policy: "NoReadAhead"
            stripe_size: 131072
            size: "200"
            raid_init_operation: "None"