---
- hosts: all
  connection: local
  name: Configure iDRAC Webserver service
  gather_facts: False

  tasks:
    - name: Configure Web Server TLS and SSL settings
      dellemc_idrac_web_server:
        idrac_ip:     "{{idrac_ip}}"
        idrac_user:   "{{idrac_user}}"
        idrac_pwd:    "{{idrac_pwd}}"
        share_name:   "{{share_name}}"
        share_user:   "{{share_user}}"
        share_pwd:    "{{share_pwd}}"
        share_mnt:    "{{share_mnt}}"
        tls_protocol: "TLS 1.1 and Higher"
        ssl_bits:     "256-Bit or higher"
      tags:
       - webserver
