---
- hosts: hosts
  connection: local
  name: Delete LC job Queue
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
  - name: Delete LC job Queue
    dellemc_delete_lc_job_queue:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"

