---
- name: Dell OpenManage Ansible iDRAC Session Management.
  hosts: idrac
  gather_facts: false

  tasks:
    - name: Perform Module operation
      block:
        - name: Create a session
          dellemc.openmanage.idrac_session:              
            hostname: 198.162.0.1
            username: username
            password: password 
            state: present
          register: authData
          delegate_to: localhost
        
        - name: Call module 1
          dellemc.openmanage.module1:
            auth_token: "{{ authData.x_auth_token }}"
          delegate_to: localhost
        
        - name: Call module 2
          dellemc.openmanage.module2:
            auth_token: "{{ authData.x_auth_token }}"
          delegate_to: localhost
        
      always:
        - name: Delete a session   
          dellemc.openmanage.idrac_session:
            state: absent
            auth_token: "{{ authData.x_auth_token }}"
            session_id: "{{ authData.session_data.Id }}"
          delegate_to: localhost
