---
- name: Storage volume configuration on iDRAC.
  hosts: idrac
  gather_facts: false
  tasks:
    - name: Create backup
      dellemc.openmanage.idrac_server_config_profile:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "user"
        idrac_password: "{{ idrac_password }}"
        validate_certs: false
        command: export
        share_name: "100.96.16.123:/nfsshare"
        target:
          - RAID
        scp_file: raid.xml
        shutdown_type: Graceful
        end_host_power_state: "On"
        job_wait: true
      delegate_to: localhost
      tags:
        - backup

    - name: Create VD with default values.
      dellemc.openmanage.idrac_storage_volume:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        validate_certs: false
        state: "create"
        controller_id: "BOSS.SL.6-1"
        stripe_size: 131072
      delegate_to: localhost
      tags:
        - create_single_volume_default

    - name: Create single VD
      dellemc.openmanage.idrac_storage_volume:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        validate_certs: false
        state: "create"
        controller_id: "BOSS.SL.6-1"
        stripe_size: 131072
        span_depth: 1
        span_length: 2
        volume_type: 'RAID 1'
        raid_reset_config: true
        volumes:
          - name: "VD_R0_0"
            drives:
              location: [3, 4]
            number_dedicated_hot_spare: 0
      check_mode: true
      delegate_to: localhost
      tags:
        - create_single_volume

    - name: Create single VD with hotspare
      dellemc.openmanage.idrac_storage_volume:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        validate_certs: false
        state: "create"
        controller_id: "RAID.Integrated.1-1"
        number_dedicated_hot_spare: 1
      delegate_to: localhost
      tags:
        - create_single_volume_hs

    - name: Create multiple volume.
      dellemc.openmanage.idrac_storage_volume:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        validate_certs: false
        state: "create"
        controller_id: "RAID.Integrated.1-1"
        capacity: 90.5
        job_wait: false
        # volumes:
        #   - name: "volume_3"
        #     drives:
        #       location: [1]
        #   - name: "volume_2"
        #     volume_type: "RAID 5"
        #     span_length: "3"
        #     span_depth: 1
        #     drives:
        #       location: [3, 4, 5]
        #     number_dedicated_hot_spare: 1
      delegate_to: localhost
      tags:
        - create_multiple_volume

    # - name: Delete single volume.
    #   dellemc.openmanage.idrac_storage_volume:
    #     idrac_ip: "{{ idrac_ip }}"
    #     idrac_user: "{{ idrac_user }}"
    #     idrac_password: "{{ idrac_password }}"
    #     ca_path: "/path/to/ca_cert.pem"
    #     state: "delete"
    #     volumes:
    #       - name: "volume_1"
    #   delegate_to: localhost
    #   tags:
    #     - delete_single_volume

    - name: Delete multiple volume
      dellemc.openmanage.idrac_storage_volume:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        validate_certs: false
        state: "delete"
        volumes:
          - name: "VD_R0_0"
          # - name: "volume_1"
          # - name: "Virtual Disk 0"
          # - name: "Virtual Disk 1"
          # - name: "Virtual Disk 2"
      delegate_to: localhost
      # check_mode: true
      tags:
        - delete_multiple_volume

    # - name: View specific volume details.
    #   dellemc.openmanage.idrac_storage_volume:
    #     idrac_ip: "{{ idrac_ip }}"
    #     idrac_user: "{{ idrac_user }}"
    #     idrac_password: "{{ idrac_password }}"
    #     validate_certs: false
    #     state: "view"
    #     controller_id: "RAID.Integrated.1-1"
    #     volume_id: "Disk.Virtual.0:RAID.Slot.1-1"
    #   delegate_to: localhost
    #   tags:
    #     - view_specific_volume

    # - name: View all volume details.
    #   dellemc.openmanage.idrac_storage_volume:
    #     idrac_ip: "{{ idrac_ip }}"
    #     idrac_user: "{{ idrac_user }}"
    #     idrac_password: "{{ idrac_password }}"
    #     validate_certs: false
    #     state: "view"
    #   delegate_to: localhost
    #   tags:
    #     - view_all_volume
