---
- name: Fetching lifecycle controller status info
  ansible.builtin.uri:
    url: "https://{{ hostname | ansible.utils.ipwrap }}:{{ https_port }}/redfish/v1/Dell/Managers/iDRAC.Embedded.1/DellLCService/Actions/DellLCService.GetRemoteServicesAPIStatus"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    ca_path: "{{ ca_path | default(omit) }}"
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
      OData-Version: "4.0"
    body_format: "json"
    method: POST
    body: {}
    return_content: true
    force_basic_auth: true
    timeout: "{{ https_timeout }}"
  check_mode: false
  register: result
  until: result.json.LCStatus == "Ready"
  retries: 240
  delay: 15
